### Load Data
First, we load the `train.csv` and `test.csv` files into pandas DataFrames.

In [12]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

df_train = pd.read_csv('/content/train.csv')
df_test = pd.read_csv('/content/test.csv')

print("Train data head:")
display(df_train.head())

print("Test data head:")
display(df_test.head())

Train data head:

,id,location_type,altitude,area_sq_m,slope_deg,soil_quality,distance_city_center_km,distance_to_school_km,distance_to_hospital_km,distance_to_market_km,...,distance_nearest_park_km,proximity_public_transport,pedestrian_index,employer_density,school_density,hospital_density,amenities_score,price_per_m2,land_area_m2,target
0,id_0,moor,860,384,29.9,0.06,14.7,0.4,6.5,0.2,...,0.59,1,0.24,19.2,2.1,4.9,0.49,19.53,384,8490.76
1,id_1,canyon,1294,543,7.1,0.63,0.8,9.0,9.5,5.2,...,1.23,1,0.62,114.9,12.5,3.8,0.81,21.63,543,13011.02
2,id_2,cliff,1130,1067,5.3,0.77,1.7,5.6,7.8,7.0,...,4.34,1,0.02,54.4,2.9,0.7,0.93,16.70,1067,16913.06
3,id_3,grove,1095,864,34.4,0.99,22.3,8.7,8.0,9.4,...,2.92,1,0.56,11.7,1.6,0.9,0.56,23.73,864,19270.35
4,id_4,grove,1638,1208,30.2,0.01,23.4,8.3,5.3,1.8,...,2.74,1,0.82,69.2,1.7,3.7,0.14,25.15,1208,30719.48

Test data head:

,id,location_type,altitude,area_sq_m,slope_deg,soil_quality,distance_city_center_km,distance_to_school_km,distance_to_hospital_km,distance_to_market_km,...,avg_property_age,distance_nearest_park_km,proximity_public_transport,pedestrian_index,employer_density,school_density,hospital_density,amenities_score,price_per_m2,land_area_m2
0,id_0,valley,887,508,34.0,0.66,1.3,4.0,4.9,6.2,...,48.9,2.47,0,0.17,23.0,2.3,0.0,0.47,17.64,508
1,id_1,gorge,2504,824,4.5,0.65,5.1,4.3,1.5,4.0,...,48.2,3.96,0,0.05,35.6,1.2,1.1,0.84,22.59,824
2,id_2,glacier,2490,707,27.6,0.15,13.4,2.6,8.9,7.9,...,21.7,1.85,1,0.53,1.4,2.3,3.0,0.26,19.73,707
3,id_3,marsh,1360,1277,16.2,0.91,33.0,2.2,1.3,3.3,...,42.6,3.58,0,0.68,55.7,2.8,2.7,0.13,22.25,1277
4,id_4,vineyard,795,952,24.6,0.41,53.0,1.1,5.9,5.3,...,6.0,2.92,0,0.66,155.5,5.5,5.2,0.37,18.07,952

### Dropping the 'id' Column
We will drop the 'id' column from both the training and testing datasets as it is typically not used for model training. We'll keep copies of the original dataframes to retain the 'id' for potential submission later.

In [13]:
df_train_original = df_train.copy() # Keep original for submission id
df_test_original = df_test.copy() # Keep original for submission id

if 'id' in df_train.columns:
    df_train = df_train.drop('id', axis=1)
if 'id' in df_test.columns:
    df_test = df_test.drop('id', axis=1)

print("df_train head after dropping 'id' column:")
display(df_train.head())

print("df_test head after dropping 'id' column:")
display(df_test.head())

df_train head after dropping 'id' column:

,location_type,altitude,area_sq_m,slope_deg,soil_quality,distance_city_center_km,distance_to_school_km,distance_to_hospital_km,distance_to_market_km,distance_to_industry_km,...,distance_nearest_park_km,proximity_public_transport,pedestrian_index,employer_density,school_density,hospital_density,amenities_score,price_per_m2,land_area_m2,target
0,moor,860,384,29.9,0.06,14.7,0.4,6.5,0.2,11.8,...,0.59,1,0.24,19.2,2.1,4.9,0.49,19.53,384,8490.76
1,canyon,1294,543,7.1,0.63,0.8,9.0,9.5,5.2,18.0,...,1.23,1,0.62,114.9,12.5,3.8,0.81,21.63,543,13011.02
2,cliff,1130,1067,5.3,0.77,1.7,5.6,7.8,7.0,15.9,...,4.34,1,0.02,54.4,2.9,0.7,0.93,16.70,1067,16913.06
3,grove,1095,864,34.4,0.99,22.3,8.7,8.0,9.4,10.9,...,2.92,1,0.56,11.7,1.6,0.9,0.56,23.73,864,19270.35
4,grove,1638,1208,30.2,0.01,23.4,8.3,5.3,1.8,8.4,...,2.74,1,0.82,69.2,1.7,3.7,0.14,25.15,1208,30719.48

df_test head after dropping 'id' column:

,location_type,altitude,area_sq_m,slope_deg,soil_quality,distance_city_center_km,distance_to_school_km,distance_to_hospital_km,distance_to_market_km,distance_to_industry_km,...,avg_property_age,distance_nearest_park_km,proximity_public_transport,pedestrian_index,employer_density,school_density,hospital_density,amenities_score,price_per_m2,land_area_m2
0,valley,887,508,34.0,0.66,1.3,4.0,4.9,6.2,17.2,...,48.9,2.47,0,0.17,23.0,2.3,0.0,0.47,17.64,508
1,gorge,2504,824,4.5,0.65,5.1,4.3,1.5,4.0,19.1,...,48.2,3.96,0,0.05,35.6,1.2,1.1,0.84,22.59,824
2,glacier,2490,707,27.6,0.15,13.4,2.6,8.9,7.9,10.2,...,21.7,1.85,1,0.53,1.4,2.3,3.0,0.26,19.73,707
3,marsh,1360,1277,16.2,0.91,33.0,2.2,1.3,3.3,10.2,...,42.6,3.58,0,0.68,55.7,2.8,2.7,0.13,22.25,1277
4,vineyard,795,952,24.6,0.41,53.0,1.1,5.9,5.3,14.5,...,6.0,2.92,0,0.66,155.5,5.5,5.2,0.37,18.07,952

### Handling Categorical Features (Label Encoding)
Categorical features need to be converted into numerical representations for machine learning models. We will use Label Encoding for this purpose. The encoder will be fitted on the training data and then used to transform both training and test data. For unseen categories in the test set, we will assign a value of -1.

In [14]:
# Identify non-numerical columns
non_numeric_cols_train = df_train.select_dtypes(include=['object', 'category']).columns
non_numeric_cols_test = df_test.select_dtypes(include=['object', 'category']).columns

# Combine all unique non-numeric columns from both dataframes
all_non_numeric_cols = list(set(list(non_numeric_cols_train) + list(non_numeric_cols_test)))

print(f"Non-numerical columns to encode: {all_non_numeric_cols}")

# Apply Label Encoding
for col in all_non_numeric_cols:
    le = LabelEncoder()
    if col in df_train.columns:
        # Fit on training data and transform
        df_train[col] = le.fit_transform(df_train[col])
        print(f"Encoded '{col}' in df_train: unique values before: {len(le.classes_)}")
    if col in df_test.columns:
        train_labels = list(le.classes_)
        mapping = {label: idx for idx, label in enumerate(train_labels)}

        def apply_label_encoding(series, mapping):
            return series.map(mapping).fillna(-1) # Use -1 for unseen categories

        df_test[col] = apply_label_encoding(df_test[col], mapping)
        df_test[col] = df_test[col].astype(int) # Convert back to int after fillna for consistency
        print(f"Encoded '{col}' in df_test using df_train's encoder.")


print("\n--- df_train head after encoding ---")
display(df_train.head())
print("\n--- df_test head after encoding ---")
display(df_test.head())

print("\n--- df_train info after encoding ---")
df_train.info()
print("\n--- df_test info after encoding ---")
df_test.info()

Non-numerical columns to encode: ['zoning_code', 'location_type', 'land_use']
Encoded 'zoning_code' in df_train: unique values before: 5
Encoded 'zoning_code' in df_test using df_train's encoder.
Encoded 'location_type' in df_train: unique values before: 40
Encoded 'location_type' in df_test using df_train's encoder.
Encoded 'land_use' in df_train: unique values before: 4
Encoded 'land_use' in df_test using df_train's encoder.

--- df_train head after encoding ---

,location_type,altitude,area_sq_m,slope_deg,soil_quality,distance_city_center_km,distance_to_school_km,distance_to_hospital_km,distance_to_market_km,distance_to_industry_km,...,distance_nearest_park_km,proximity_public_transport,pedestrian_index,employer_density,school_density,hospital_density,amenities_score,price_per_m2,land_area_m2,target
0,21,860,384,29.9,0.06,14.7,0.4,6.5,0.2,11.8,...,0.59,1,0.24,19.2,2.1,4.9,0.49,19.53,384,8490.76
1,2,1294,543,7.1,0.63,0.8,9.0,9.5,5.2,18.0,...,1.23,1,0.62,114.9,12.5,3.8,0.81,21.63,543,13011.02
2,3,1130,1067,5.3,0.77,1.7,5.6,7.8,7.0,15.9,...,4.34,1,0.02,54.4,2.9,0.7,0.93,16.70,1067,16913.06
3,11,1095,864,34.4,0.99,22.3,8.7,8.0,9.4,10.9,...,2.92,1,0.56,11.7,1.6,0.9,0.56,23.73,864,19270.35
4,11,1638,1208,30.2,0.01,23.4,8.3,5.3,1.8,8.4,...,2.74,1,0.82,69.2,1.7,3.7,0.14,25.15,1208,30719.48

--- df_test head after encoding ---

,location_type,altitude,area_sq_m,slope_deg,soil_quality,distance_city_center_km,distance_to_school_km,distance_to_hospital_km,distance_to_market_km,distance_to_industry_km,...,avg_property_age,distance_nearest_park_km,proximity_public_transport,pedestrian_index,employer_density,school_density,hospital_density,amenities_score,price_per_m2,land_area_m2
0,36,887,508,34.0,0.66,1.3,4.0,4.9,6.2,17.2,...,48.9,2.47,0,0.17,23.0,2.3,0.0,0.47,17.64,508
1,10,2504,824,4.5,0.65,5.1,4.3,1.5,4.0,19.1,...,48.2,3.96,0,0.05,35.6,1.2,1.1,0.84,22.59,824
2,9,2490,707,27.6,0.15,13.4,2.6,8.9,7.9,10.2,...,21.7,1.85,1,0.53,1.4,2.3,3.0,0.26,19.73,707
3,19,1360,1277,16.2,0.91,33.0,2.2,1.3,3.3,10.2,...,42.6,3.58,0,0.68,55.7,2.8,2.7,0.13,22.25,1277
4,37,795,952,24.6,0.41,53.0,1.1,5.9,5.3,14.5,...,6.0,2.92,0,0.66,155.5,5.5,5.2,0.37,18.07,952

--- df_train info after encoding ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 44 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   location_type               1500 non-null   int64
 1   altitude                    1500 non-null   int64
 2   area_sq_m                   1500 non-null   int64
 3   slope_deg                   1500 non-null   float64
 4   soil_quality                1500 non-null   float64
 5   distance_city_center_km     1500 non-null   float64
 6   distance_to_school_km       1500 non-null   float64
 7   distance_to_hospital_km     1500 non-null   float64
 8   distance_to_market_km       1500 non-null   float64
 9   distance_to_industry_km     1500 non-null   float64
 10  proximity_road              1500 non-null   int64
 11  proximity_water             1500 non-null   int64
 12  urban_zone                  1500 non-null   int64
 13  protected_area              1500 non-null   int64
 14  flood_risk                  1500 non-null   int64
 15  earthquake_risk             1500 non-null   int64
 16  average_temp_C              1500 non-null   float64
 17  annual_rainfall_mm          1500 non-null   float64
 18  sun_hours_per_year          1500 non-null   float64
 19  crime_rate                  1500 non-null   float64
 20  air_quality_index           1500 non-null   float64
 21  noise_pollution_index       1500 non-null   float64
 22  internet_access             1500 non-null   int64
 23  median_income_area          1500 non-null   float64
 24  unemployment_rate           1500 non-null   float64
 25  GDP_growth_rate             1500 non-null   float64
 26  interest_rate               1500 non-null   float64
 27  population_density          1500 non-null   float64
 28  historical_site             1500 non-null   int64
 29  neighborhood_quality        1500 non-null   float64
 30  land_use                    1500 non-null   int64
 31  zoning_code                 1500 non-null   int64
 32  tax_rate                    1500 non-null   float64
 33  avg_property_age            1500 non-null   float64
 34  distance_nearest_park_km    1500 non-null   float64
 35  proximity_public_transport  1500 non-null   int64
 36  pedestrian_index            1500 non-null   float64
 37  employer_density            1500 non-null   float64
 38  school_density              1500 non-null   float64
 39  hospital_density            1500 non-null   float64
 40  amenities_score             1500 non-null   float64
 41  price_per_m2                1500 non-null   float64
 42  land_area_m2                1500 non-null   int64
 43  target                      1500 non-null   float64
dtypes: float64(29), int64(15)
memory usage: 515.8 KB

--- df_test info after encoding ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 43 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   location_type               1200 non-null   int64
 1   altitude                    1200 non-null   int64
 2   area_sq_m                   1200 non-null   int64
 3   slope_deg                   1200 non-null   float64
 4   soil_quality                1200 non-null   float64
 5   distance_city_center_km     1200 non-null   float64
 6   distance_to_school_km       1200 non-null   float64
 7   distance_to_hospital_km     1200 non-null   float64
 8   distance_to_market_km       1200 non-null   float64
 9   distance_to_industry_km     1200 non-null   float64
 10  proximity_road              1200 non-null   int64
 11  proximity_water             1200 non-null   int64
 12  urban_zone                  1200 non-null   int64
 13  protected_area              1200 non-null   int64
 14  flood_risk                  1200 non-null   int64
 15  earthquake_risk             1200 non-null   int64
 16  average_temp_C              1200 non-null   float64
 17  annual_rainfall_mm          1200 non-null   float64
 18  sun_hours_per_year          1200 non-null   float64
 19  crime_rate                  1200 non-null   float64
 20  air_quality_index           1200 non-null   float64
 21  noise_pollution_index       1200 non-null   float64
 22  internet_access             1200 non-null   int64
 23  median_income_area          1200 non-null   float64
 24  unemployment_rate           1200 non-null   float64
 25  GDP_growth_rate             1200 non-null   float64
 26  interest_rate               1200 non-null   float64
 27  population_density          1200 non-null   float64
 28  historical_site             1200 non-null   int64
 29  neighborhood_quality        1200 non-null   float64
 30  land_use                    1200 non-null   int64
 31  zoning_code                 1200 non-null   int64
 32  tax_rate                    1200 non-null   float64
 33  avg_property_age            1200 non-null   float64
 34  distance_nearest_park_km    1200 non-null   float64
 35  proximity_public_transport  1200 non-null   int64
 36  pedestrian_index            1200 non-null   float64
 37  employer_density            1200 non-null   float64
 38  school_density              1200 non-null   float64
 39  hospital_density            1200 non-null   float64
 40  amenities_score             1200 non-null   float64
 41  price_per_m2                1200 non-null   float64
 42  land_area_m2                1200 non-null   int64
dtypes: float64(28), int64(15)
memory usage: 403.3 KB

### Handling Outliers using IQR Method
To manage outliers, I'll implement a capping strategy based on the Interquartile Range (IQR). This involves defining lower and upper bounds (Q1 - 1.5 * IQR and Q3 + 1.5 * IQR, respectively) and then replacing any values outside these bounds with the respective boundary value. This approach helps to mitigate the impact of extreme values while retaining all data points.

In [15]:
def cap_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Cap the values
    df[column] = np.where(df[column] < lower_bound, lower_bound, df[column])
    df[column] = np.where(df[column] > upper_bound, upper_bound, df[column])
    return df

# Identify numerical columns (excluding the target in df_train)
numerical_cols_train = df_train.select_dtypes(include=np.number).columns.tolist()
if 'target' in numerical_cols_train:
    numerical_cols_train.remove('target')
numerical_cols_test = df_test.select_dtypes(include=np.number).columns.tolist()

print("Applying outlier capping to numerical columns in df_train:")
for col in numerical_cols_train:
    df_train = cap_outliers_iqr(df_train, col)
    print(f"  - Capped outliers for: {col}")

print("\nApplying outlier capping to numerical columns in df_test:")
for col in numerical_cols_test:
    df_test = cap_outliers_iqr(df_test, col)
    print(f"  - Capped outliers for: {col}")

print("\n--- df_train descriptive statistics after outlier capping ---")
display(df_train.describe())

print("\n--- df_test descriptive statistics after outlier capping ---")
display(df_test.describe())

Applying outlier capping to numerical columns in df_train:
  - Capped outliers for: location_type
  - Capped outliers for: altitude
  - Capped outliers for: area_sq_m
  - Capped outliers for: slope_deg
  - Capped outliers for: soil_quality
  - Capped outliers for: distance_city_center_km
  - Capped outliers for: distance_to_school_km
  - Capped outliers for: distance_to_hospital_km
  - Capped outliers for: distance_to_market_km
  - Capped outliers for: distance_to_industry_km
  - Capped outliers for: proximity_road
  - Capped outliers for: proximity_water
  - Capped outliers for: urban_zone
  - Capped outliers for: protected_area
  - Capped outliers for: flood_risk
  - Capped outliers for: earthquake_risk
  - Capped outliers for: average_temp_C
  - Capped outliers for: annual_rainfall_mm
  - Capped outliers for: sun_hours_per_year
  - Capped outliers for: crime_rate
  - Capped outliers for: air_quality_index
  - Capped outliers for: noise_pollution_index
  - Capped outliers for: internet_access
  - Capped outliers for: median_income_area
  - Capped outliers for: unemployment_rate
  - Capped outliers for: GDP_growth_rate
  - Capped outliers for: interest_rate
  - Capped outliers for: population_density
  - Capped outliers for: historical_site
  - Capped outliers for: neighborhood_quality
  - Capped outliers for: land_use
  - Capped outliers for: zoning_code
  - Capped outliers for: tax_rate
  - Capped outliers for: avg_property_age
  - Capped outliers for: distance_nearest_park_km
  - Capped outliers for: proximity_public_transport
  - Capped outliers for: pedestrian_index
  - Capped outliers for: employer_density
  - Capped outliers for: school_density
  - Capped outliers for: hospital_density
  - Capped outliers for: amenities_score
  - Capped outliers for: price_per_m2
  - Capped outliers for: land_area_m2

Applying outlier capping to numerical columns in df_test:
  - Capped outliers for: location_type
  - Capped outliers for: altitude
  - Capped outliers for: area_sq_m
  - Capped outliers for: slope_deg
  - Capped outliers for: soil_quality
  - Capped outliers for: distance_city_center_km
  - Capped outliers for: distance_to_school_km
  - Capped outliers for: distance_to_hospital_km
  - Capped outliers for: distance_to_market_km
  - Capped outliers for: distance_to_industry_km
  - Capped outliers for: proximity_road
  - Capped outliers for: proximity_water
  - Capped outliers for: urban_zone
  - Capped outliers for: protected_area
  - Capped outliers for: flood_risk
  - Capped outliers for: earthquake_risk
  - Capped outliers for: average_temp_C
  - Capped outliers for: annual_rainfall_mm
  - Capped outliers for: sun_hours_per_year
  - Capped outliers for: crime_rate
  - Capped outliers for: air_quality_index
  - Capped outliers for: noise_pollution_index
  - Capped outliers for: internet_access
  - Capped outliers for: median_income_area
  - Capped outliers for: unemployment_rate
  - Capped outliers for: GDP_growth_rate
  - Capped outliers for: interest_rate
  - Capped outliers for: population_density
  - Capped outliers for: historical_site
  - Capped outliers for: neighborhood_quality
  - Capped outliers for: land_use
  - Capped outliers for: zoning_code
  - Capped outliers for: tax_rate
  - Capped outliers for: avg_property_age
  - Capped outliers for: distance_nearest_park_km
  - Capped outliers for: proximity_public_transport
  - Capped outliers for: pedestrian_index
  - Capped outliers for: employer_density
  - Capped outliers for: school_density
  - Capped outliers for: hospital_density
  - Capped outliers for: amenities_score
  - Capped outliers for: price_per_m2
  - Capped outliers for: land_area_m2

--- df_train descriptive statistics after outlier capping ---

,location_type,altitude,area_sq_m,slope_deg,soil_quality,distance_city_center_km,distance_to_school_km,distance_to_hospital_km,distance_to_market_km,distance_to_industry_km,...,distance_nearest_park_km,proximity_public_transport,pedestrian_index,employer_density,school_density,hospital_density,amenities_score,price_per_m2,land_area_m2,target
count,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,...,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.00000,1500.000000,1500.000000,1500.000000
mean,19.654000,1510.307333,808.798000,22.595333,0.488200,18.744217,5.063467,5.037867,4.949200,10.059333,...,2.562053,0.506000,0.501420,47.089283,4.662133,1.967267,0.49954,20.128029,808.798000,16336.820593
std,11.531707,869.062246,199.542869,12.912443,0.289817,16.118608,2.924687,2.836951,2.891921,5.679881,...,1.451473,0.500131,0.285589,41.318587,4.016419,1.739871,0.28330,4.946298,199.542869,5963.580009
min,0.000000,1.000000,271.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,7.221250,271.000000,1352.530000
25%,9.000000,767.500000,676.000000,11.400000,0.240000,6.075000,2.600000,2.700000,2.500000,5.200000,...,1.300000,0.000000,0.260000,13.800000,1.600000,0.600000,0.26000,16.990000,676.000000,12010.932500
50%,20.000000,1502.000000,809.000000,23.000000,0.480000,14.200000,5.050000,5.100000,4.900000,10.200000,...,2.630000,1.000000,0.500000,34.200000,3.400000,1.500000,0.49000,20.265000,809.000000,15824.475000
75%,30.000000,2221.000000,946.000000,33.825000,0.740000,27.050000,7.600000,7.400000,7.400000,14.900000,...,3.832500,1.000000,0.742500,68.250000,6.700000,2.900000,0.74000,23.502500,946.000000,20174.357500
max,39.000000,2999.000000,1351.000000,44.900000,1.000000,58.512500,10.000000,10.000000,10.000000,20.000000,...,5.000000,1.000000,1.000000,149.925000,14.350000,6.350000,1.00000,33.271250,1351.000000,37781.130000

--- df_test descriptive statistics after outlier capping ---

,location_type,altitude,area_sq_m,slope_deg,soil_quality,distance_city_center_km,distance_to_school_km,distance_to_hospital_km,distance_to_market_km,distance_to_industry_km,...,avg_property_age,distance_nearest_park_km,proximity_public_transport,pedestrian_index,employer_density,school_density,hospital_density,amenities_score,price_per_m2,land_area_m2
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,...,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,19.444167,1475.580833,790.104271,22.559583,0.510492,18.795167,5.004833,5.036417,4.923917,10.122167,...,24.701167,2.520833,0.497500,0.500400,47.167219,4.956625,1.886083,0.504717,20.274898,790.104271
std,11.338460,862.969281,199.025979,12.922704,0.294477,16.759052,2.897981,2.850793,2.826758,5.803889,...,14.169708,1.415389,0.500202,0.294192,40.976507,4.435899,1.624221,0.284728,4.870641,199.025979
min,0.000000,0.000000,260.125000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.292500,260.125000
25%,9.000000,729.750000,661.000000,11.600000,0.260000,5.500000,2.400000,2.575000,2.575000,5.200000,...,12.375000,1.330000,0.000000,0.250000,14.350000,1.400000,0.600000,0.250000,16.967500,661.000000
50%,20.000000,1486.000000,782.500000,22.000000,0.530000,13.300000,5.100000,5.150000,4.900000,10.300000,...,24.800000,2.490000,0.000000,0.510000,34.700000,3.600000,1.400000,0.510000,20.230000,782.500000
75%,29.000000,2221.750000,928.250000,33.425000,0.770000,28.000000,7.525000,7.600000,7.325000,15.000000,...,36.900000,3.710000,1.000000,0.760000,69.225000,7.100000,2.700000,0.742500,23.417500,928.250000
max,39.000000,2998.000000,1329.125000,44.900000,1.000000,61.750000,10.000000,10.000000,10.000000,20.000000,...,50.000000,5.000000,1.000000,1.000000,151.537500,15.650000,5.850000,1.000000,33.092500,1329.125000

### Feature and Target Scaling using MinMaxScaler
We will now apply Min-Max Scaling to all numerical features in both the training and test datasets, as well as to the target variable in the training set. This transformation scales features to a given range (typically 0 to 1), which can be beneficial for many machine learning algorithms. The scaler will be fitted on the training data and then used to transform both training and test data to prevent data leakage.

In [20]:
# Separate features (X) and target (y) from the training data
X = df_train.drop('target', axis=1)
y = df_train['target']

# Initialize MinMaxScaler for features
feature_scaler = MinMaxScaler()

# Fit the scaler on training features and transform them
X_train_scaled = feature_scaler.fit_transform(X)
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X.columns)

# Transform the test features using the same scaler fitted on the training data
df_test_scaled = feature_scaler.transform(df_test)
df_test_scaled = pd.DataFrame(df_test_scaled, columns=df_test.columns)

# Assign X_train to the scaled features
X_train = X_train_scaled.copy()

print("\n--- X_train (scaled features) head ---")
display(X_train.head())

print("\n--- df_test (scaled features) head ---")
display(df_test_scaled.head())

--- X_train (scaled features) head ---

,location_type,altitude,area_sq_m,slope_deg,soil_quality,distance_city_center_km,distance_to_school_km,distance_to_hospital_km,distance_to_market_km,distance_to_industry_km,...,avg_property_age,distance_nearest_park_km,proximity_public_transport,pedestrian_index,employer_density,school_density,hospital_density,amenities_score,price_per_m2,land_area_m2
0,0.538462,0.286524,0.104630,0.665924,0.06,0.251228,0.04,0.65,0.02,0.590,...,0.226908,0.118,1.0,0.24,0.128064,0.146341,0.771654,0.49,0.472505,0.104630
1,0.051282,0.431288,0.251852,0.158129,0.63,0.013672,0.90,0.95,0.52,0.900,...,0.377510,0.246,1.0,0.62,0.766383,0.871080,0.598425,0.81,0.553119,0.251852
2,0.076923,0.376584,0.737037,0.118040,0.77,0.029054,0.56,0.78,0.70,0.795,...,0.626506,0.868,1.0,0.02,0.362848,0.202091,0.110236,0.93,0.363868,0.737037
3,0.282051,0.364910,0.549074,0.766147,0.99,0.381115,0.87,0.80,0.94,0.545,...,0.562249,0.584,1.0,0.56,0.078039,0.111498,0.141732,0.56,0.633733,0.549074
4,0.282051,0.546031,0.867593,0.672606,0.01,0.399915,0.83,0.53,0.18,0.420,...,0.640562,0.548,1.0,0.82,0.461564,0.118467,0.582677,0.14,0.688244,0.867593

--- df_test (scaled features) head ---

,location_type,altitude,area_sq_m,slope_deg,soil_quality,distance_city_center_km,distance_to_school_km,distance_to_hospital_km,distance_to_market_km,distance_to_industry_km,...,avg_property_age,distance_nearest_park_km,proximity_public_transport,pedestrian_index,employer_density,school_density,hospital_density,amenities_score,price_per_m2,land_area_m2
0,0.923077,0.295530,0.219444,0.757238,0.66,0.022217,0.40,0.49,0.62,0.860,...,0.979920,0.494,0.0,0.17,0.153410,0.160279,0.000000,0.47,0.399952,0.219444
1,0.256410,0.834890,0.512037,0.100223,0.65,0.087161,0.43,0.15,0.40,0.955,...,0.965863,0.792,0.0,0.05,0.237452,0.083624,0.173228,0.84,0.589971,0.512037
2,0.230769,0.830220,0.403704,0.614699,0.15,0.229011,0.26,0.89,0.79,0.510,...,0.433735,0.370,1.0,0.53,0.009338,0.160279,0.472441,0.26,0.480182,0.403704
3,0.487179,0.453302,0.931481,0.360802,0.91,0.563982,0.22,0.13,0.33,0.510,...,0.853414,0.716,0.0,0.68,0.371519,0.195122,0.425197,0.13,0.576919,0.931481
4,0.948718,0.264843,0.630556,0.547884,0.41,0.905789,0.11,0.59,0.53,0.725,...,0.118474,0.584,0.0,0.66,1.010755,0.383275,0.818898,0.37,0.416459,0.630556

In [21]:
# Initialize MinMaxScaler for the target variable
target_scaler = MinMaxScaler()

# Fit the scaler on the training target and transform it
y_train_scaled = target_scaler.fit_transform(y.values.reshape(-1, 1))
y_train_scaled = pd.Series(y_train_scaled.flatten(), name='target_scaled')

print("\n--- y_train_scaled head ---")
display(y_train_scaled.head())

--- y_train_scaled head ---

0    0.195951
1    0.320037
2    0.427151
3    0.491861
4    0.806151
Name: target_scaled, dtype: float64

In [17]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 44 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   location_type               1500 non-null   float64
 1   altitude                    1500 non-null   float64
 2   area_sq_m                   1500 non-null   float64
 3   slope_deg                   1500 non-null   float64
 4   soil_quality                1500 non-null   float64
 5   distance_city_center_km     1500 non-null   float64
 6   distance_to_school_km       1500 non-null   float64
 7   distance_to_hospital_km     1500 non-null   float64
 8   distance_to_market_km       1500 non-null   float64
 9   distance_to_industry_km     1500 non-null   float64
 10  proximity_road              1500 non-null   float64
 11  proximity_water             1500 non-null   float64
 12  urban_zone                  1500 non-null   float64
 13  protected_area              1500 non-null   float64
 14  flood_risk                  1500 non-null   float64
 15  earthquake_risk             1500 non-null   float64
 16  average_temp_C              1500 non-null   float64
 17  annual_rainfall_mm          1500 non-null   float64
 18  sun_hours_per_year          1500 non-null   float64
 19  crime_rate                  1500 non-null   float64
 20  air_quality_index           1500 non-null   float64
 21  noise_pollution_index       1500 non-null   float64
 22  internet_access             1500 non-null   float64
 23  median_income_area          1500 non-null   float64
 24  unemployment_rate           1500 non-null   float64
 25  GDP_growth_rate             1500 non-null   float64
 26  interest_rate               1500 non-null   float64
 27  population_density          1500 non-null   float64
 28  historical_site             1500 non-null   float64
 29  neighborhood_quality        1500 non-null   float64
 30  land_use                    1500 non-null   float64
 31  zoning_code                 1500 non-null   float64
 32  tax_rate                    1500 non-null   float64
 33  avg_property_age            1500 non-null   float64
 34  distance_nearest_park_km    1500 non-null   float64
 35  proximity_public_transport  1500 non-null   float64
 36  pedestrian_index            1500 non-null   float64
 37  employer_density            1500 non-null   float64
 38  school_density              1500 non-null   float64
 39  hospital_density            1500 non-null   float64
 40  amenities_score             1500 non-null   float64
 41  price_per_m2                1500 non-null   float64
 42  land_area_m2                1500 non-null   float64
 43  target                      1500 non-null   float64
dtypes: float64(44)
memory usage: 515.8 KB

### Prepare Features and Target for Modeling
We now define `X_train` (features for training), `y_train_scaled` (scaled target for training), and `X_test` (features for generating predictions).

In [22]:
# X_train is already defined and scaled from the previous step
X_train = X_train # Renaming for clarity as X_train already contains features from df_train

# X_test is the entire df_test as it does not contain a target column
X_test = df_test.copy()

# y_test is not available for the test dataset
y_test = None

print("\n--- X_train head after separation (scaled features) ---")
display(X_train.head())

print("\n--- X_test head after separation (scaled features) ---")
display(X_test.head())

print("\n--- y_train_scaled head after separation ---")
display(y_train_scaled.head())

--- X_train head after separation (scaled features) ---

,location_type,altitude,area_sq_m,slope_deg,soil_quality,distance_city_center_km,distance_to_school_km,distance_to_hospital_km,distance_to_market_km,distance_to_industry_km,...,avg_property_age,distance_nearest_park_km,proximity_public_transport,pedestrian_index,employer_density,school_density,hospital_density,amenities_score,price_per_m2,land_area_m2
0,0.538462,0.286524,0.104630,0.665924,0.06,0.251228,0.04,0.65,0.02,0.590,...,0.226908,0.118,1.0,0.24,0.128064,0.146341,0.771654,0.49,0.472505,0.104630
1,0.051282,0.431288,0.251852,0.158129,0.63,0.013672,0.90,0.95,0.52,0.900,...,0.377510,0.246,1.0,0.62,0.766383,0.871080,0.598425,0.81,0.553119,0.251852
2,0.076923,0.376584,0.737037,0.118040,0.77,0.029054,0.56,0.78,0.70,0.795,...,0.626506,0.868,1.0,0.02,0.362848,0.202091,0.110236,0.93,0.363868,0.737037
3,0.282051,0.364910,0.549074,0.766147,0.99,0.381115,0.87,0.80,0.94,0.545,...,0.562249,0.584,1.0,0.56,0.078039,0.111498,0.141732,0.56,0.633733,0.549074
4,0.282051,0.546031,0.867593,0.672606,0.01,0.399915,0.83,0.53,0.18,0.420,...,0.640562,0.548,1.0,0.82,0.461564,0.118467,0.582677,0.14,0.688244,0.867593

--- X_test head after separation (scaled features) ---

,location_type,altitude,area_sq_m,slope_deg,soil_quality,distance_city_center_km,distance_to_school_km,distance_to_hospital_km,distance_to_market_km,distance_to_industry_km,...,avg_property_age,distance_nearest_park_km,proximity_public_transport,pedestrian_index,employer_density,school_density,hospital_density,amenities_score,price_per_m2,land_area_m2
0,36.0,887.0,508.0,34.0,0.66,1.3,4.0,4.9,6.2,17.2,...,48.9,2.47,0.0,0.17,23.0000,2.3,0.0,0.47,17.64,508.0
1,10.0,2504.0,824.0,4.5,0.65,5.1,4.3,1.5,4.0,19.1,...,48.2,3.96,0.0,0.05,35.6000,1.2,1.1,0.84,22.59,824.0
2,9.0,2490.0,707.0,27.6,0.15,13.4,2.6,8.9,7.9,10.2,...,21.7,1.85,1.0,0.53,1.4000,2.3,3.0,0.26,19.73,707.0
3,19.0,1360.0,1277.0,16.2,0.91,33.0,2.2,1.3,3.3,10.2,...,42.6,3.58,0.0,0.68,55.7000,2.8,2.7,0.13,22.25,1277.0
4,37.0,795.0,952.0,24.6,0.41,53.0,1.1,5.9,5.3,14.5,...,6.0,2.92,0.0,0.66,151.5375,5.5,5.2,0.37,18.07,952.0

--- y_train_scaled head after separation ---

0    0.195951
1    0.320037
2    0.427151
3    0.491861
4    0.806151
Name: target_scaled, dtype: float64

### Split Training Data for Validation
To evaluate model performance objectively, we split the preprocessed training data (`X_train`, `y_train_scaled`) into an 80/20 training/validation set. This allows us to train models on `X_train_new` and `y_train_new_scaled` and evaluate them on `X_test_new` and `y_test_new_scaled`.

In [23]:
# Split the scaled training data into training and a new 'test' (validation) set
X_train_new, X_test_new, y_train_new_scaled, y_test_new_scaled = train_test_split(
    X_train, y_train_scaled, test_size=0.2, random_state=42
)

print("Shape of X_train_new:", X_train_new.shape)
print("Shape of X_test_new:", X_test_new.shape)
print("Shape of y_train_new_scaled:", y_train_new_scaled.shape)
print("Shape of y_test_new_scaled:", y_test_new_scaled.shape)

Shape of X_train_new: (1200, 43)
Shape of X_test_new: (300, 43)
Shape of y_train_new_scaled: (1200,)
Shape of y_test_new_scaled: (300,)

### Linear Regression Model Training and Evaluation
We will start by training a simple Linear Regression model as a baseline. After training, we will evaluate its performance using metrics such as R-squared, Mean Squared Error (MSE), and Mean Absolute Error (MAE) on both the training and validation sets.

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

# Initialize and train the Linear Regression model
linear_model = LinearRegression()
linear_model.fit(X_train_new, y_train_new_scaled)

# Make predictions on the training and validation sets
y_train_pred_new_scaled = linear_model.predict(X_train_new)
y_test_pred_new_scaled = linear_model.predict(X_test_new)

# Evaluate the model on the training set
r2_train_new_scaled = r2_score(y_train_new_scaled, y_train_pred_new_scaled)
mse_train_new_scaled = mean_squared_error(y_train_new_scaled, y_train_pred_new_scaled)
mae_train_new_scaled = mean_absolute_error(y_train_new_scaled, y_train_pred_new_scaled)
rmse_train_new_scaled = np.sqrt(mse_train_new_scaled)

# Adjusted R-squared for training set
n_train_new = X_train_new.shape[0]
p_train_new = X_train_new.shape[1]
adjusted_r2_train_new_scaled = 1 - (1 - r2_train_new_scaled) * (n_train_new - 1) / (n_train_new - p_train_new - 1)

# Evaluate the model on the validation set
r2_test_new_scaled = r2_score(y_test_new_scaled, y_test_pred_new_scaled)
mse_test_new_scaled = mean_squared_error(y_test_new_scaled, y_test_pred_new_scaled)
mae_test_new_scaled = mean_absolute_error(y_test_new_scaled, y_test_pred_new_scaled)
rmse_test_new_scaled = np.sqrt(mse_test_new_scaled)

# Adjusted R-squared for validation set
n_test_new = X_test_new.shape[0]
p_test_new = X_test_new.shape[1]
adjusted_r2_test_new_scaled = 1 - (1 - r2_test_new_scaled) * (n_test_new - 1) / (n_test_new - p_test_new - 1)

print("\nLinear Regression Model Performance (Scaled Data):\n")
print(f"Training R-squared: {r2_train_new_scaled:.4f}")
print(f"Training Adjusted R-squared: {adjusted_r2_train_new_scaled:.4f}")
print(f"Training MSE: {mse_train_new_scaled:.4f}")
print(f"Training RMSE: {rmse_train_new_scaled:.4f}")
print(f"Training MAE: {mae_train_new_scaled:.4f}")

print(f"\nValidation R-squared: {r2_test_new_scaled:.4f}")
print(f"Validation Adjusted R-squared: {adjusted_r2_test_new_scaled:.4f}")
print(f"Validation MSE: {mse_test_new_scaled:.4f}")
print(f"Validation RMSE: {rmse_test_new_scaled:.4f}")
print(f"Validation MAE: {mae_test_new_scaled:.4f}")

Linear Regression Model Performance (Scaled Data):

Training R-squared: 0.9488
Training Adjusted R-squared: 0.9469
Training MSE: 0.0013
Training RMSE: 0.0364
Training MAE: 0.0277

Validation R-squared: 0.9572
Validation Adjusted R-squared: 0.9500
Validation MSE: 0.0013
Validation RMSE: 0.0361
Validation MAE: 0.0279

### Lasso Regression Model Training and Evaluation
Lasso (Least Absolute Shrinkage and Selection Operator) regression is a linear model that estimates sparse coefficients. It performs L1 regularization, which can lead to feature selection by shrinking some coefficients to zero.

In [25]:
from sklearn.linear_model import Lasso

# Initialize and train the Lasso Regression model
lasso_model = Lasso(random_state=42) # Using default alpha for now, can be tuned later
lasso_model.fit(X_train_new, y_train_new_scaled)

# Make predictions on the training and validation sets
y_train_pred_lasso_scaled = lasso_model.predict(X_train_new)
y_test_pred_lasso_scaled = lasso_model.predict(X_test_new)

# Evaluate the model on the training set
r2_train_lasso_scaled = r2_score(y_train_new_scaled, y_train_pred_lasso_scaled)
mse_train_lasso_scaled = mean_squared_error(y_train_new_scaled, y_train_pred_lasso_scaled)
mae_train_lasso_scaled = mean_absolute_error(y_train_new_scaled, y_train_pred_lasso_scaled)
rmse_train_lasso_scaled = np.sqrt(mse_train_lasso_scaled)

# Adjusted R-squared for training set
adjusted_r2_train_lasso_scaled = 1 - (1 - r2_train_lasso_scaled) * (n_train_new - 1) / (n_train_new - p_train_new - 1)

# Evaluate the model on the validation set
r2_test_lasso_scaled = r2_score(y_test_new_scaled, y_test_pred_lasso_scaled)
mse_test_lasso_scaled = mean_squared_error(y_test_new_scaled, y_test_pred_lasso_scaled)
mae_test_lasso_scaled = mean_absolute_error(y_test_new_scaled, y_test_pred_lasso_scaled)
rmse_test_lasso_scaled = np.sqrt(mse_test_lasso_scaled)

# Adjusted R-squared for validation set
adjusted_r2_test_lasso_scaled = 1 - (1 - r2_test_lasso_scaled) * (n_test_new - 1) / (n_test_new - p_test_new - 1)

print("\nLasso Regression Model Performance (Scaled Data):\n")
print(f"Training R-squared: {r2_train_lasso_scaled:.4f}")
print(f"Training Adjusted R-squared: {adjusted_r2_train_lasso_scaled:.4f}")
print(f"Training MSE: {mse_train_lasso_scaled:.4f}")
print(f"Training RMSE: {rmse_train_lasso_scaled:.4f}")
print(f"Training MAE: {mae_train_lasso_scaled:.4f}")

print(f"\nValidation R-squared: {r2_test_lasso_scaled:.4f}")
print(f"Validation Adjusted R-squared: {adjusted_r2_test_lasso_scaled:.4f}")
print(f"Validation MSE: {mse_test_lasso_scaled:.4f}")
print(f"Validation RMSE: {rmse_test_lasso_scaled:.4f}")
print(f"Validation MAE: {mae_test_lasso_scaled:.4f}")

Lasso Regression Model Performance (Scaled Data):

Training R-squared: 0.0000
Training Adjusted R-squared: -0.0372
Training MSE: 0.0258
Training RMSE: 0.1608
Training MAE: 0.1293

Validation R-squared: -0.0000
Validation Adjusted R-squared: -0.1680
Validation MSE: 0.0305
Validation RMSE: 0.1747
Validation MAE: 0.1411

### Ridge Regression Model Training and Evaluation
Ridge regression is another linear model that addresses some of the problems of Ordinary Least Squares by imposing a penalty on the size of coefficients. It performs L2 regularization, which helps in preventing overfitting and handling multicollinearity among features.

In [26]:
from sklearn.linear_model import Ridge

# Initialize and train the Ridge Regression model
ridge_model = Ridge(random_state=42) # Using default alpha for now, can be tuned later
ridge_model.fit(X_train_new, y_train_new_scaled)

# Make predictions on the training and validation sets
y_train_pred_ridge_scaled = ridge_model.predict(X_train_new)
y_test_pred_ridge_scaled = ridge_model.predict(X_test_new)

# Evaluate the model on the training set
r2_train_ridge_scaled = r2_score(y_train_new_scaled, y_train_pred_ridge_scaled)
mse_train_ridge_scaled = mean_squared_error(y_train_new_scaled, y_train_pred_ridge_scaled)
mae_train_ridge_scaled = mean_absolute_error(y_train_new_scaled, y_train_pred_ridge_scaled)
rmse_train_ridge_scaled = np.sqrt(mse_train_ridge_scaled)

# Adjusted R-squared for training set
adjusted_r2_train_ridge_scaled = 1 - (1 - r2_train_ridge_scaled) * (n_train_new - 1) / (n_train_new - p_train_new - 1)

# Evaluate the model on the validation set
r2_test_ridge_scaled = r2_score(y_test_new_scaled, y_test_pred_ridge_scaled)
mse_test_ridge_scaled = mean_squared_error(y_test_new_scaled, y_test_pred_ridge_scaled)
mae_test_ridge_scaled = mean_absolute_error(y_test_new_scaled, y_test_pred_ridge_scaled)
rmse_test_ridge_scaled = np.sqrt(mse_test_ridge_scaled)

# Adjusted R-squared for validation set
adjusted_r2_test_ridge_scaled = 1 - (1 - r2_test_ridge_scaled) * (n_test_new - 1) / (n_test_new - p_test_new - 1)

print("\nRidge Regression Model Performance (Scaled Data):\n")
print(f"Training R-squared: {r2_train_ridge_scaled:.4f}")
print(f"Training Adjusted R-squared: {adjusted_r2_train_ridge_scaled:.4f}")
print(f"Training MSE: {mse_train_ridge_scaled:.4f}")
print(f"Training RMSE: {rmse_train_ridge_scaled:.4f}")
print(f"Training MAE: {mae_train_ridge_scaled:.4f}")

print(f"\nValidation R-squared: {r2_test_ridge_scaled:.4f}")
print(f"Validation Adjusted R-squared: {adjusted_r2_test_ridge_scaled:.4f}")
print(f"Validation MSE: {mse_test_ridge_scaled:.4f}")
print(f"Validation RMSE: {rmse_test_ridge_scaled:.4f}")
print(f"Validation MAE: {mae_test_ridge_scaled:.4f}")

Ridge Regression Model Performance (Scaled Data):

Training R-squared: 0.9485
Training Adjusted R-squared: 0.9465
Training MSE: 0.0013
Training RMSE: 0.0365
Training MAE: 0.0277

Validation R-squared: 0.9583
Validation Adjusted R-squared: 0.9513
Validation MSE: 0.0013
Validation RMSE: 0.0357
Validation MAE: 0.0274

### Elastic Net Regression Model Training and Evaluation
Elastic Net regression is a hybrid regularization technique that combines both L1 (Lasso) and L2 (Ridge) penalties. This allows it to learn from multiple features and perform feature selection simultaneously, often resulting in better performance when there are highly correlated features.

In [29]:
from sklearn.linear_model import ElasticNet

# Initialize and train the Elastic Net Regression model
elastic_net_model = ElasticNet(random_state=42) # Using default alpha and l1_ratio for now, can be tuned later
elastic_net_model.fit(X_train_new, y_train_new_scaled)

# Make predictions on the training and validation sets
y_train_pred_elastic_scaled = elastic_net_model.predict(X_train_new)
y_test_pred_elastic_scaled = elastic_net_model.predict(X_test_new)

# Evaluate the model on the training set
r2_train_elastic_scaled = r2_score(y_train_new_scaled, y_train_pred_elastic_scaled)
mse_train_elastic_scaled = mean_squared_error(y_train_new_scaled, y_train_pred_elastic_scaled)
mae_train_elastic_scaled = mean_absolute_error(y_train_new_scaled, y_train_pred_elastic_scaled)
rmse_train_elastic_scaled = np.sqrt(mse_train_elastic_scaled)

# Adjusted R-squared for training set
adjusted_r2_train_elastic_scaled = 1 - (1 - r2_train_elastic_scaled) * (n_train_new - 1) / (n_train_new - p_train_new - 1)

# Evaluate the model on the validation set
r2_test_elastic_scaled = r2_score(y_test_new_scaled, y_test_pred_elastic_scaled)
mse_test_elastic_scaled = mean_squared_error(y_test_new_scaled, y_test_pred_elastic_scaled)
mae_test_elastic_scaled = mean_absolute_error(y_test_new_scaled, y_test_pred_elastic_scaled)
rmse_test_elastic_scaled = np.sqrt(mse_test_elastic_scaled)

# Adjusted R-squared for validation set
adjusted_r2_test_elastic_scaled = 1 - (1 - r2_test_elastic_scaled) * (n_test_new - 1) / (n_test_new - p_test_new - 1)

print("\nElastic Net Regression Model Performance (Scaled Data):\n")
print(f"Training R-squared: {r2_train_elastic_scaled:.4f}")
print(f"Training Adjusted R-squared: {adjusted_r2_train_elastic_scaled:.4f}")
print(f"Training MSE: {mse_train_elastic_scaled:.4f}")
print(f"Training RMSE: {rmse_train_elastic_scaled:.4f}")
print(f"Training MAE: {mae_train_elastic_scaled:.4f}")

print(f"\nValidation R-squared: {r2_test_elastic_scaled:.4f}")
print(f"Validation Adjusted R-squared: {adjusted_r2_test_elastic_scaled:.4f}")
print(f"Validation MSE: {mse_test_elastic_scaled:.4f}")
print(f"Validation RMSE: {rmse_test_elastic_scaled:.4f}")
print(f"Validation MAE: {mae_test_elastic_scaled:.4f}")

Elastic Net Regression Model Performance (Scaled Data):

Training R-squared: 0.0000
Training Adjusted R-squared: -0.0372
Training MSE: 0.0258
Training RMSE: 0.1608
Training MAE: 0.1293

Validation R-squared: -0.0000
Validation Adjusted R-squared: -0.1680
Validation MSE: 0.0305
Validation RMSE: 0.1747
Validation MAE: 0.1411

### Hyperparameter Tuning for Ridge Regression using GridSearchCV
Given the promising performance of the Ridge Regression model, we will now perform hyperparameter tuning to find its optimal `alpha` value. We will use `GridSearchCV` to systematically search through a range of `alpha` values and identify the one that yields the best performance on our validation set. This helps prevent overfitting and ensures the model generalizes well to unseen data.

In [28]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge

# Define the parameter grid for alpha
param_grid = {'alpha': np.logspace(-4, 2, 100)}

# Initialize GridSearchCV with Ridge regressor
# Using neg_mean_squared_error as scoring to optimize for lower MSE
grid_search_ridge = GridSearchCV(Ridge(random_state=42), param_grid, cv=5, scoring='neg_mean_squared_error', n_jobs=-1)

# Fit GridSearchCV to the training data
grid_search_ridge.fit(X_train_new, y_train_new_scaled)

# Get the best alpha parameter
best_alpha_ridge = grid_search_ridge.best_params_['alpha']
print(f"Best alpha for Ridge Regression: {best_alpha_ridge:.4f}")

# Train the Ridge model with the best alpha
best_ridge_model = Ridge(alpha=best_alpha_ridge, random_state=42)
best_ridge_model.fit(X_train_new, y_train_new_scaled)

# Make predictions on the training and validation sets with the best model
y_train_pred_tuned_ridge_scaled = best_ridge_model.predict(X_train_new)
y_test_pred_tuned_ridge_scaled = best_ridge_model.predict(X_test_new)

# Evaluate the tuned model on the training set
r2_train_tuned_ridge_scaled = r2_score(y_train_new_scaled, y_train_pred_tuned_ridge_scaled)
mse_train_tuned_ridge_scaled = mean_squared_error(y_train_new_scaled, y_train_pred_tuned_ridge_scaled)
mae_train_tuned_ridge_scaled = mean_absolute_error(y_train_new_scaled, y_train_pred_tuned_ridge_scaled)
rmse_train_tuned_ridge_scaled = np.sqrt(mse_train_tuned_ridge_scaled)
adjusted_r2_train_tuned_ridge_scaled = 1 - (1 - r2_train_tuned_ridge_scaled) * (n_train_new - 1) / (n_train_new - p_train_new - 1)

# Evaluate the tuned model on the validation set
r2_test_tuned_ridge_scaled = r2_score(y_test_new_scaled, y_test_pred_tuned_ridge_scaled)
mse_test_tuned_ridge_scaled = mean_squared_error(y_test_new_scaled, y_test_pred_tuned_ridge_scaled)
mae_test_tuned_ridge_scaled = mean_absolute_error(y_test_new_scaled, y_test_pred_tuned_ridge_scaled)
rmse_test_tuned_ridge_scaled = np.sqrt(mse_test_tuned_ridge_scaled)
adjusted_r2_test_tuned_ridge_scaled = 1 - (1 - r2_test_tuned_ridge_scaled) * (n_test_new - 1) / (n_test_new - p_test_new - 1)

print("\nOptimized Ridge Regression Model Performance (Scaled Data):\n")
print(f"Training R-squared: {r2_train_tuned_ridge_scaled:.4f}")
print(f"Training Adjusted R-squared: {adjusted_r2_train_tuned_ridge_scaled:.4f}")
print(f"Training MSE: {mse_train_tuned_ridge_scaled:.4f}")
print(f"Training RMSE: {rmse_train_tuned_ridge_scaled:.4f}")
print(f"Training MAE: {mae_train_tuned_ridge_scaled:.4f}")

print(f"\nValidation R-squared: {r2_test_tuned_ridge_scaled:.4f}")
print(f"Validation Adjusted R-squared: {adjusted_r2_test_tuned_ridge_scaled:.4f}")
print(f"Validation MSE: {mse_test_tuned_ridge_scaled:.4f}")
print(f"Validation RMSE: {rmse_test_tuned_ridge_scaled:.4f}")
print(f"Validation MAE: {mae_test_tuned_ridge_scaled:.4f}")

Best alpha for Ridge Regression: 0.1630

Optimized Ridge Regression Model Performance (Scaled Data):

Training R-squared: 0.9488
Training Adjusted R-squared: 0.9469
Training MSE: 0.0013
Training RMSE: 0.0364
Training MAE: 0.0277

Validation R-squared: 0.9574
Validation Adjusted R-squared: 0.9503
Validation MSE: 0.0013
Validation RMSE: 0.0360
Validation MAE: 0.0278

### Generate Predictions for Submission
Using the best-performing and tuned Ridge Regression model, we will now generate predictions on the preprocessed test dataset (`X_test`). Since our model was trained on scaled target values, we must inverse transform these predictions to bring them back to the original scale before saving them for submission.

In [32]:
# Generate predictions on the scaled X_test data using the best Ridge model
predictions_scaled = best_ridge_model.predict(X_test)

# Inverse transform the scaled predictions to the original scale
predictions_original_scale = target_scaler.inverse_transform(predictions_scaled.reshape(-1, 1))

# Flatten the predictions to a 1D array
predictions_original_scale = predictions_original_scale.flatten()

# Create a submission DataFrame
submission_df = pd.DataFrame({'id': df_test_original['id'], 'target': predictions_original_scale})

# Display the first few rows of the submission DataFrame
print("Submission DataFrame Head:")
display(submission_df.head())

# Save the submission file to a CSV
submission_filename = '/content/sample_submission.csv'
submission_df.to_csv(submission_filename, index=False)

print(f"Predictions saved to {submission_filename}")

Submission DataFrame Head:

     id        target
0  id_0  1.420758e+07
1  id_1  2.083132e+07
2  id_2  1.881389e+07
3  id_3  3.178054e+07
4  id_4  2.485311e+07

Predictions saved to /content/sample_submission.csv